name: MassimilianoAmbrosini
favicon: null
layout_spectrum: 0.4920845206361264
typography_spectrum: 0.37255572620779276
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.091715382412076
  lightness: 0.5494565546978265
  saturation: 0.6760724659543484
  rhythmicContrast: 0.7142979470081627
purpose: []
